Script.ReloadScript("SCRIPTS/Entities/AI/Ark/ArkCannibal_x.lua")
Script.ReloadScript("SCRIPTS/Entities/actor/BasicActor.lua")
Script.ReloadScript("SCRIPTS/Entities/AI/Shared/BasicAI.lua")
Script.ReloadScript("SCRIPTS/Entities/actor/ArkNpc.lua")
Script.ReloadScript("SCRIPTS/Entities/AI/Ark/ArkMimic.lua")
CreateActorForAISubclass(ArkCannibal_x)
CreateArkNpc(ArkMimic_x)
ArkCannibal = CreateAISubclass(ArkCannibal_x, ArkMimic_x)
InitActorForAISubclass(ArkCannibal_x)
ArkCannibal:Expose()
