Script.ReloadScript("SCRIPTS/Entities/AI/Ark/ArkNightmareLunar_x.lua")
Script.ReloadScript("SCRIPTS/Entities/actor/BasicActor.lua")
Script.ReloadScript("SCRIPTS/Entities/AI/Shared/BasicAI.lua")
Script.ReloadScript("SCRIPTS/Entities/actor/ArkNpc.lua")
Script.ReloadScript("SCRIPTS/Entities/AI/Ark/ArkNightmare.lua")
CreateActorForAISubclass(ArkNightmareLunar_x)
CreateArkNpc(ArkNightmare_x)
ArkNightmareLunar = CreateAISubclass(ArkNightmareLunar_x, ArkNightmare_x)
InitActorForAISubclass(ArkNightmareLunar_x)
ArkNightmareLunar:Expose()
