Script.ReloadScript("SCRIPTS/Entities/AI/Ark/ArkOperatorMining_x.lua")
Script.ReloadScript("SCRIPTS/Entities/actor/BasicActor.lua")
Script.ReloadScript("SCRIPTS/Entities/AI/Shared/BasicAI.lua")
Script.ReloadScript("SCRIPTS/Entities/actor/ArkNpc.lua")
Script.ReloadScript("SCRIPTS/Entities/AI/Ark/ArkOperator.lua")
CreateActorForAISubclass(ArkOperatorMining_x)
CreateArkNpc(ArkOperator_x)
ArkOperatorMining = CreateAISubclass(ArkOperatorMining_x, ArkOperator_x)
InitActorForAISubclass(ArkOperatorMining_x)
ArkOperatorMining:Expose()
