Script.ReloadScript("SCRIPTS/Entities/AI/Ark/ArkPhantomCannibal_x.lua")
Script.ReloadScript("SCRIPTS/Entities/actor/BasicActor.lua")
Script.ReloadScript("SCRIPTS/Entities/AI/Shared/BasicAI.lua")
Script.ReloadScript("SCRIPTS/Entities/actor/ArkNpc.lua")
Script.ReloadScript("SCRIPTS/Entities/AI/Ark/ArkBeta.lua")
CreateActorForAISubclass(ArkPhantomCannibal_x)
CreateArkNpc(ArkBeta_x)
ArkPhantomCannibal = CreateAISubclass(ArkPhantomCannibal_x, ArkBeta_x)
InitActorForAISubclass(ArkPhantomCannibal_x)
ArkPhantomCannibal:Expose()
